minVersion: 1.0.0
changelogPolicy: auto
artifactProvider:
  name: none
statusProvider:
  name: github
  config:
    contexts:
      - 'vroom-build-docker-image-commit (sentryio)'
targets:
  - name: github
  - id: release
    name: docker
    source: us.gcr.io/sentryio/vroom
    target: getsentry/vroom
  - id: latest
    name: docker
    source: us.gcr.io/sentryio/vroom
    target: getsentry/vroom
    targetFormat: '{{{target}}}:latest'
