minVersion: 1.0.0
changelogPolicy: auto
artifactProvider:
  name: none
statusProvider:
  name: github
  config:
    contexts:
      - 'build-vroom (sentryio)'
targets:
  - name: github
  - id: release
    name: docker
    source: us-central1-docker.pkg.dev/sentryio/vroom/vroom
    target: getsentry/vroom
  - id: latest
    name: docker
    source: us-central1-docker.pkg.dev/sentryio/vroom/vroom
    target: getsentry/vroom
    targetFormat: '{{{target}}}:latest'
preReleaseCommand: ""
