version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    #- depguard
    - dogsled
    #- dupl
    - errcheck
    - forbidigo
    - gochecknoinits
    #- goconst
    #- gocritic
    - gocyclo
    - godot
    #- gosec
    #- gosimple
    #- govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    #- staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
