linters:
  disable-all: true
  enable:
    - bodyclose
    #- depguard
    - dogsled
    #- dupl
    - errcheck
    - exportloopref
    - forbidigo
    - gochecknoinits
    #- goconst
    #- gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    #- gosec
    #- gosimple
    #- govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    #- staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
output:
  print-linter-name: true
  show-stats: true
