steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/sentryio/vroom:$COMMIT_SHA',
    '-t', 'us-central1-docker.pkg.dev/sentryio/vroom:latest',
    '.',
  ]
images: [
  'us-central1-docker.pkg.dev/sentryio/vroom:$COMMIT_SHA',
  'us-central1-docker.pkg.dev/sentryio/vroom:latest',
]
