format_version: 10
pipelines:
    deploy-vroom:
        environment_variables:
            GITHUB_TOKEN: "{{SECRET:[devinfra-github][token]}}"
            GCP_PROJECT: internal-sentry
            GKE_CLUSTER: zdpwkxst
            GKE_REGION: us-central1
            GKE_CLUSTER_ZONE: b
            GKE_BASTION_ZONE: b
            ENVIRONMENT: production
        group: vroom
        lock_behavior: unlockWhenFinished
        materials:
            vroom_repo:
                git: git@github.com:getsentry/vroom.git
                shallow_clone: true
                destination: vroom
                branch: main
        stages:
            - checks:
                  fetch_materials: true
                  approval:
                      type: manual
                  jobs:
                      check_ci_status:
                          timeout: 600
                          elastic_profile_id: vroom
                          tasks:
                              - script: |
                                    /devinfra/scripts/checks/githubactions/checkruns.py \
                                        getsentry/vroom \
                                        ${GO_REVISION_VROOM_REPO} \
                                        test-vroom
                      check_build_status:
                          timeout: 600
                          elastic_profile_id: vroom
                          tasks:
                              - script: |
                                 /devinfra/scripts/checks/googlecloud/checkcloudbuild.py \
                                    ${GO_REVISION_VROOM_REPO} \
                                    ${GCP_PROJECT} \
                                    "us.gcr.io/${GCP_PROJECT}/vroom"
            - deploy-canary:
                  approval:
                      type: success
                      allow_only_on_success: true
                  jobs:
                      deploy-to-k8s:
                          timeout: 600
                          elastic_profile_id: vroom
                          tasks:
                              - script: |
                                   USE_GKE_GCLOUD_AUTH_PLUGIN=True \
                                      gcloud --project "$GCP_PROJECT" \
                                        container clusters get-credentials "$GKE_CLUSTER" \
                                        --zone "${GKE_REGION}-${GKE_CLUSTER_ZONE}" \
                                      && tmpdir=$(mktemp -d) \
                                      && ssh-keygen -q -t ed25519 -N '' -f "${tmpdir}/google_compute_engine" \
                                      && gcloud compute ssh "dicd-gkehop-${GKE_CLUSTER}" \
                                        --ssh-key-file="${tmpdir}/google_compute_engine" \
                                        --tunnel-through-iap \
                                        "--project=${GCP_PROJECT}" \
                                        "--zone=${GKE_REGION}-${GKE_BASTION_ZONE}" \
                                        -- -4 -L8888:127.0.0.1:8888 -N -q -f
                              - script: |
                                   /devinfra/scripts/k8s/k8s-deploy.py \
                                      --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                      --label-selector="service=vroom,component=default,environment=${ENVIRONMENT},env=canary" \
                                      --image="us.gcr.io/${GCP_PROJECT}/vroom:${GO_REVISION_VROOM_REPO}" \
                                      --container-name="vroom"
                              - script: |
                                   /devinfra/scripts/canary/canarychecks.py \
                                     --wait-minutes=5
            - deploy-primary:
                  approval:
                      type: success
                      allow_only_on_success: true
                  jobs:
                      deploy-to-k8s:
                          timeout: 600
                          elastic_profile_id: vroom
                          tasks:
                              - script: |
                                   USE_GKE_GCLOUD_AUTH_PLUGIN=True \
                                      gcloud --project "$GCP_PROJECT" \
                                        container clusters get-credentials "$GKE_CLUSTER" \
                                        --zone "${GKE_REGION}-${GKE_CLUSTER_ZONE}" \
                                      && tmpdir=$(mktemp -d) \
                                      && ssh-keygen -q -t ed25519 -N '' -f "${tmpdir}/google_compute_engine" \
                                      && gcloud compute ssh "dicd-gkehop-${GKE_CLUSTER}" \
                                        --ssh-key-file="${tmpdir}/google_compute_engine" \
                                        --tunnel-through-iap \
                                        "--project=${GCP_PROJECT}" \
                                        "--zone=${GKE_REGION}-${GKE_BASTION_ZONE}" \
                                        -- -4 -L8888:127.0.0.1:8888 -N -q -f
                              - script: |
                                   /devinfra/scripts/k8s/k8s-deploy.py \
                                      --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                      --label-selector="service=vroom,component=default,environment=${ENVIRONMENT}" \
                                      --image="us.gcr.io/${GCP_PROJECT}/vroom:${GO_REVISION_VROOM_REPO}" \
                                      --container-name="vroom"
