name: changelog
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:
    name: changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const changelog = require('./.github/actions/changelog/index.js')
            await changelog({github, context, core})
