name: Lint Deployment Pipelines
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  render:
    name: Render GoCD Pipelines with Jsonnet
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: getsentry/action-gocd-jsonnet@v1
          with:
            jb-install: true
            jsonnet-dir: gocd/templates
            generated-dir: gocd/generated-pipelines
