name: Release GHCR Versioned Image

on:
  release:
    types: [prereleased, released]

jobs:
  release-ghcr-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release version
        run: |
          docker buildx imagetools create --tag \
           ghcr.io/getsentry/vroom:${{ github.ref_name }} \
           ghcr.io/getsentry/vroom:${{ github.sha }}

      - name: Tag latest version
        run: |
          docker buildx imagetools create --tag \
           ghcr.io/getsentry/vroom:latest \
           ghcr.io/getsentry/vroom:${{ github.sha }}
